### ISSUE TITLE
cli53 silently hangs when run within a github actions workflow

### ISSUE THREAD

**Issue by garylawuk** [barnybug/cli53#277]
### Issue type

 - Bug report

### cli53 version (cli53 --version)
Run /usr/local/bin/cli53 --version && uname -a

cli53 version master
Darwin Mac-144.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

### OS / Platform

MacOS10.14 -- and I get the same results on ubuntu-latest

### Steps to reproduce

Using github
1. create secrets for  AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY
2. create a workflow under
.github/workflows/aws-dns-backup.yml
with the contents below:-

```
name: DNS backup

on:
  schedule:
    - cron:  '30 * * * *'

jobs:
  build:
    name: AWS DNS backup update
    runs-on: macOS-10.14
    steps:
      - name: install the AWS CLI
        run: brew install  awscli
      - name: install the CLI53
        run: brew install cli53
      - name: prep the local files
        uses: actions/checkout@v1
      - name: debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_R53_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_R53_SECRET_ACCESS_KEY }}
        run:  /usr/local/bin/cli53 --version && uname -a
      - name: list test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_R53_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_R53_SECRET_ACCESS_KEY }}
        run:  /usr/local/bin/cli53 list
```

### Expected behaviour

the console log should show a list of zones 

### Actual behaviour

the command never finishes or produces any output

### Have you checked if the documentation has the information you require?

yes -- I've noticed you're using github actions to run tests.  Perhaps a full build from source will work where the pre-pack binaries fail. I've not tried that.

### Could you contribute a fix or help testing with this issue?

if this can be reproduced I'd be delighted to help with fixing it.  I'd also be prepared to help with a public 'actions' provider for cli53.

**Comment by garylawuk** [comment]
Could be similar to this:
https://github.com/barnybug/cli53/issues/239
I'm going to try and reproduce with the 'debug' flag

**Comment by garylawuk** [comment]
updating the workflow to this:

```
name: DNS backup

on:
  schedule:
    - cron:  '45 * * * *'

jobs:
  build:
    name: AWS DNS backup update
    runs-on: macOS-10.14
    steps:
      - name: install the AWS CLI
        run: brew install  awscli
      - name: install the CLI53
        run: brew install cli53
      - name: install coreutils
        run: brew install coreutils
      - name: prep the local files
        uses: actions/checkout@v1
      - name: debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_R53_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_R53_SECRET_ACCESS_KEY }}
        run:  /usr/local/bin/cli53 --version && uname -a
      - name: list test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TEST_R53_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_R53_SECRET_ACCESS_KEY }}
        run:  /usr/local/bin/gtimeout 10 /usr/local/bin/cli53 list --debug
```
results in an error, repeating endlessly until stopped by the timeout (note -- actual signature redacted):

```
Run /usr/local/bin/gtimeout 10 /usr/local/bin/cli53 list --debug
  /usr/local/bin/gtimeout 10 /usr/local/bin/cli53 list --debug
  shell: /bin/bash -e {0}
  env:
    AWS_ACCESS_KEY_ID: ***
  
    AWS_SECRET_ACCESS_KEY: ***
DEBUG ERROR: Request route53/ListHostedZones:
---[ REQUEST DUMP ERROR ]-----------------------------
net/http: invalid header field value "AWS4-HMAC-SHA256 Credential=***, SignedHeaders=host;x-amz-date, Signature=***" for key Authorization
------------------------------------------------------

```
